default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>

development:
  <<: *default
  database: familles_rurales_development

test:
  <<: *default
  database: familles_rurales_test

production:
  <<: *default
  host: <%= ENV.fetch("DB_HOST", "familles_rurales-db") %>
  database: <%= ENV.fetch("DB_NAME", "familles_rurales_production") %>
  username: <%= ENV.fetch("DB_USER", "familles_rurales") %>
  password: <%= ENV["DB_PASSWORD"] || ENV["POSTGRES_PASSWORD"] %>
